global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Remote write configuration to send metrics to Mimir
remote_write:
  - url: http://mimir:8080/api/v1/push
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
    # Optional: Add external labels to identify the source
    write_relabel_configs:
      - source_labels: [__name__]
        target_label: __tmp_prometheus_job_name
        replacement: prometheus

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'mimir'
    static_configs:
      - targets: ['mimir:8080']
